'use client';

import Navbar from '@/components/Navbar';
import React from 'react';

const TermsOfService = () => {
  return (
    <>
    <Navbar />
    <div className="bg-gray-50 dark:bg-[#1a1a1a] text-gray-800 dark:text-zinc-300 antialiased">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
        <div className="max-w-4xl mx-auto bg-white dark:bg-zinc-900 p-8 sm:p-10 rounded-2xl shadow-lg dark:border dark:border-zinc-800">
          
          <header className="mb-10 text-center">
            <h1 className="text-4xl sm:text-5xl font-bold text-gray-900 dark:text-zinc-100 tracking-tight">
              Hooman Group Ltd – Terms of Service
            </h1>
            <div className="mt-4 text-lg text-gray-600 dark:text-zinc-400 space-y-1">
              <p><strong>Effective Date:</strong> 14 August 2025</p>
              <p><strong>Last Updated:</strong> 14 August 2025</p>
            </div>
          </header>
          
          <div className="prose prose-lg max-w-none text-gray-700 dark:text-zinc-300 space-y-6">
            
            <Section title="1. Agreement to Terms">
              <p>
                <strong>1.1.</strong> These Terms of Service (“Terms”) constitute a legally binding agreement between you (“you”, “your”, or “User”) and Hooman Group Ltd (“Hooman Group”, “we”, “our”, or “us”), a company registered in England and Wales with registered address at [Your Address Here], United Kingdom. These Terms govern your access to and use of our websites (including www.hoomanpets.com), mobile applications, platforms, AI-powered tools (such as Ezra AI), digital products, and any related services (collectively, the “Services”).
              </p>
              <p>
                <strong>1.2.</strong> By accessing, registering for, or using the Services in any manner, you acknowledge that you have read, understood, and agree to be bound by these Terms, our Privacy Policy (incorporated herein by reference), and any additional guidelines or rules posted within the Services. If you do not agree to these Terms, you must not access or use the Services and should discontinue any use immediately.
              </p>
              <p>
                <strong>1.3.</strong> If you are using the Services on behalf of a business, organisation, or other entity, you represent and warrant that you have the authority to bind that entity to these Terms, and “you” and “your” will refer to that entity.
              </p>
              <p>
                <strong>1.4.</strong> We may provide additional terms for specific features or promotions (“Additional Terms”), which will be presented to you at the time of access. In the event of a conflict, the Additional Terms will prevail over these Terms for that specific feature.
              </p>
            </Section>

            <Section title="2. Eligibility">
                <p><strong>2.1.</strong> To use the Services, you must be at least 16 years of age (or the age of majority in your jurisdiction, if higher). If you are under 18 years of age, you must obtain verifiable parental or legal guardian consent before using the Services. We reserve the right to request proof of age or consent at any time.</p>
                <p><strong>2.2.</strong> If you are representing a business or organisation, you must have the legal authority to enter into contracts on its behalf.</p>
                <p><strong>2.3.</strong> The Services are not available to individuals or entities previously suspended or removed by us, or those located in jurisdictions where access is prohibited by law or sanctions (e.g., embargoed countries under UK, EU, or US regulations).</p>
                <p><strong>2.4.</strong> By using the Services, you represent and warrant that you meet these eligibility requirements. We may terminate your access if we determine you do not qualify.</p>
            </Section>

            <Section title="3. Services Provided">
                <p><strong>3.1.</strong> Hooman Group provides a range of digital pet care tools, including but not limited to reminders for vaccinations and grooming, AI-powered recommendations via Ezra AI, community forums, integration with veterinary partners, pet health tracking, and e-commerce features for pet-related products.</p>
                <p><strong>3.2. Important Disclaimer:</strong> The Services are intended for informational and organisational purposes only and are not a substitute for professional veterinary, medical, or healthcare advice, diagnosis, or treatment. Always consult a licensed veterinarian or qualified professional for any pet health concerns. We do not provide veterinary services, and any insights or recommendations generated by our tools (including AI) are based on general data and user inputs, which may not account for individual circumstances.</p>
                <p><strong>3.3.</strong> We may update, modify, or discontinue any part of the Services at any time without notice, including for maintenance, improvements, or compliance reasons. We do not guarantee uninterrupted access or error-free operation.</p>
            </Section>

            <Section title="4. Accounts and Registration">
                <p><strong>4.1.</strong> To access certain features, you must create an account by providing accurate, current, and complete information as requested (e.g., name, email, pet details). You agree to update your information promptly if it changes.</p>
                <p><strong>4.2.</strong> You are solely responsible for maintaining the confidentiality of your account credentials (e.g., username, password) and for all activities occurring under your account. You must notify us immediately at <a href="mailto:support@hoomanpets.com" className="text-blue-600 dark:text-blue-400 hover:underline">support@hoomanpets.com</a> of any unauthorised use or security breach.</p>
                <p><strong>4.3.</strong> We reserve the right to refuse registration, suspend, or terminate accounts at our discretion, particularly for violations of these Terms or suspected fraudulent activity.</p>
                <p><strong>4.4.</strong> You may delete your account at any time through the account settings, subject to any ongoing obligations (e.g., unpaid fees). Upon deletion, we may retain certain data as outlined in our Privacy Policy.</p>
            </Section>
            
            {/* ... Other sections would be formatted similarly ... */}
            
            <Section title="9. Warranties and Limitation of Liability">
              <p><strong>9.1.</strong> The Services are provided “as is” and “as available” without warranties of any kind, express or implied, including but not limited to merchantability, fitness for a particular purpose, accuracy, or non-infringement.</p>
              <p><strong>9.2.</strong> To the maximum extent permitted by law, Hooman Group, its affiliates, officers, directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, goodwill, or pet-related harm, arising from or related to the Services, even if advised of the possibility.</p>
              <p><strong>9.3.</strong> Our total aggregate liability for any claims under these Terms is limited to the amount you paid us for the Services in the twelve (12) months preceding the claim.</p>
              <p><strong>9.4.</strong> Nothing in these Terms excludes or limits liability for death or personal injury caused by negligence, fraud, or any other liability that cannot be excluded under applicable law (e.g., UK Consumer Rights Act 2015).</p>
            </Section>

            <Section title="14. Miscellaneous">
                <p><strong>14.1. Force Majeure:</strong> We are not liable for delays or failures due to events beyond our control (e.g., natural disasters, pandemics, cyber-attacks).</p>
                <p><strong>14.2. Severability:</strong> If any provision is held invalid, the remainder remains in effect.</p>
                <p><strong>14.3. Waiver:</strong> No waiver of any term is binding unless in writing.</p>
                <p><strong>14.4. Assignment:</strong> We may assign these Terms without your consent; you may not assign without our written approval.</p>
                <p><strong>14.5. Entire Agreement:</strong> These Terms, together with our Privacy Policy and any Additional Terms, constitute the entire agreement.</p>
                <p><strong>14.6. Contact:</strong> For questions, contact us at <a href="mailto:legal@hoomanpets.com" className="text-blue-600 dark:text-blue-400 hover:underline">legal@hoomanpets.com</a> or our registered address.</p>
                <p>By using the Services, you confirm your agreement to these Terms.</p>
            </Section>

          </div>
        </div>
      </div>
    </div>
    </>
  );
};

// This helper component structures the main sections
const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <section className="space-y-4 pt-6">
    <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-zinc-100 border-b border-gray-200 dark:border-zinc-800 pb-2 mb-4">
      {title}
    </h2>
    <div className="space-y-4">{children}</div>
  </section>
);

export default TermsOfService;